### PR TITLE
Ekitabu/feature/dev

### PR DESCRIPTION
**Pull request by brettins**

### CODE REVIEW

**Comment by brettins** [comment]
I'm having issues with analytics in this build - for some reason the production version is only firing openBook events. However, in the interests of having a working build with the latest Readium code, I'm opening this pull request.

**Review by kevinmainairungu — COMMENTED** [review]
@brettins checked the database and attached a screenshot. It's the said case
Screen Shot 2020-10-22 at 9 26 34 PM

**Comment by brettins** [comment]
I'm not sure what you're trying to show me or asking, @kevinmainairungu

**Comment by kevinmainairungu** [comment]
> I'm not sure what you're trying to show me or asking, @kevinmainairungu

@brettins  I'm just confirming that the production version is only firing OpenBook events.

**Review by kevinmainairungu — APPROVED** [review]
@brettins reviewed the code and approved.

**Pull request merged**
